console.time('MyCode took:');
console.log('hello');
console.log(4**3);
console.log(true);
console.log([1,2,3,4]);
console.log({harry:'this',marks:34});
console.table({harry:'this',marks:34});
console.warn('hello warning here');
//console.clear();
console.timeEnd('MyCode took:');
// console.assert(566<189,'This is not possible');
console.error('This is an error');
